/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountDto } from '../../models/account-dto';

export interface GetAllAccounts$Params {
}

export function getAllAccounts(http: HttpClient, rootUrl: string, params?: GetAllAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllAccounts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AccountDto>>;
    })
  );
}

getAllAccounts.PATH = '/api/accounts';
