/**
 * POS API Documentation
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountDTO } from './accountDTO';
import { SortInfo } from './sortInfo';


export interface PagingResultAccountDTO { 
    totalDisplayRecords?: number;
    totalRecords?: number;
    data?: Array<AccountDTO>;
    start?: number;
    end?: number;
    page?: number;
    totalPages?: number;
    sort?: Array<SortInfo>;
}

