/**
 * POS API Documentation
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UpdateProfileRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProfileControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getProfile(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param updateProfileRequest 
     */
    saveProfile(updateProfileRequest: UpdateProfileRequest, extraHttpRequestParams?: any): Observable<object>;

}
