/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OfficeConfig } from '../../models/office-config';

export interface SaveConfig$Params {
      body: OfficeConfig
}

export function saveConfig(http: HttpClient, rootUrl: string, params: SaveConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<OfficeConfig>> {
  const rb = new RequestBuilder(rootUrl, saveConfig.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OfficeConfig>;
    })
  );
}

saveConfig.PATH = '/api/config';
