/**
 * POS API Documentation
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { OfficeConfig } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OfficeConfigControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getConfig(extraHttpRequestParams?: any): Observable<OfficeConfig>;

    /**
     * 
     * 
     * @param officeConfig 
     */
    saveConfig(officeConfig: OfficeConfig, extraHttpRequestParams?: any): Observable<OfficeConfig>;

}
