/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccountDto } from '../models/account-dto';
import { getAllAccounts } from '../fn/account-management/get-all-accounts';
import { GetAllAccounts$Params } from '../fn/account-management/get-all-accounts';
import { PagingResultAccountDto } from '../models/paging-result-account-dto';
import { searchAccounts } from '../fn/account-management/search-accounts';
import { SearchAccounts$Params } from '../fn/account-management/search-accounts';


/**
 * APIs for managing accounts
 */
@Injectable({ providedIn: 'root' })
export class AccountManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllAccounts()` */
  static readonly GetAllAccountsPath = '/api/accounts';

  /**
   * Get all accounts.
   *
   * Retrieves a list of all accounts in the system
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAccounts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccounts$Response(params?: GetAllAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountDto>>> {
    return getAllAccounts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all accounts.
   *
   * Retrieves a list of all accounts in the system
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAccounts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccounts(params?: GetAllAccounts$Params, context?: HttpContext): Observable<Array<AccountDto>> {
    return this.getAllAccounts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AccountDto>>): Array<AccountDto> => r.body)
    );
  }

  /** Path part for operation `searchAccounts()` */
  static readonly SearchAccountsPath = '/api/accounts/search';

  /**
   * Search accounts.
   *
   * Search accounts with pagination and sorting
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchAccounts()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchAccounts$Response(params?: SearchAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagingResultAccountDto>> {
    return searchAccounts(this.http, this.rootUrl, params, context);
  }

  /**
   * Search accounts.
   *
   * Search accounts with pagination and sorting
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchAccounts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchAccounts(params?: SearchAccounts$Params, context?: HttpContext): Observable<PagingResultAccountDto> {
    return this.searchAccounts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagingResultAccountDto>): PagingResultAccountDto => r.body)
    );
  }

}
