/**
 * POS API Documentation
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Account { 
    id?: number;
    code?: string;
    name?: string;
    level?: number;
    type?: Account.TypeEnum;
    category?: Account.CategoryEnum;
    currency?: string;
    createdAt?: string;
    updatedAt?: string;
    cashBank?: boolean;
    fxDefault?: boolean;
    active?: boolean;
}
export namespace Account {
    export const TypeEnum = {
        H: 'H',
        D: 'D'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const CategoryEnum = {
        Asset: 'Asset',
        Liability: 'Liability',
        Equity: 'Equity',
        Income: 'Income',
        CostOfSales: 'Cost_of_Sales',
        Expense: 'Expense',
        OtherIncome: 'Other_Income',
        OtherExpense: 'Other_Expense'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


