/**
 * POS API Documentation
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountDTO { 
    id?: number;
    code?: string;
    name?: string;
    level?: number;
    type?: AccountDTO.TypeEnum;
    category?: AccountDTO.CategoryEnum;
    cashBank?: boolean;
    fxDefault?: boolean;
    currency?: string;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    parent?: AccountDTO;
}
export namespace AccountDTO {
    export const TypeEnum = {
        H: 'H',
        D: 'D'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const CategoryEnum = {
        Asset: 'Asset',
        Equity: 'Equity',
        Expense: 'Expense',
        Liability: 'Liability',
        Revenue: 'Revenue'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


