/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfficeConfig {
  endMonth?: number;
  headOfficeCode?: string;
  id?: number;
  officeName?: string;
  startMonth?: number;
  startYear?: number;
  timezone?: string;
}
