/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  firstName?: string;
  id?: number;
  lastName?: string;
  password?: string;
  role?: string;
  username?: string;
}
